remote_theme: pages-themes/modernist@v0.2.0
plugins: 
- jekyll-remote-theme 
# theme: jeykll-theme-Modernist 
title: ECE 4160 HOMEPAGE (ed433)
author: Edwin Dake (ed433)
description: Lab Reports go here! 

